name: nfl
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.0
  http: ^1.2.2
  intl: ^0.20.1
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  device_orientation: ^1.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  marquee: ^2.3.0
  marquee_list: ^1.0.0
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^19.2.0
  permission_handler: ^12.0.1
  video_player: ^2.9.2
  chewie: ^1.8.5
  webview_flutter: ^4.13.0
  new_version_plus: ^0.1.0
  package_info_plus: ^8.3.1
  youtube_player_flutter: ^9.1.1
  firebase_database: ^12.0.0
  cloud_firestore: ^6.0.0
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/nflimage.png"

flutter:
  uses-material-design: true
  assets:
    - assets/nflimage.png